<a href="https://colab.research.google.com/github/titusnkumara/pythonII/blob/master/sec_numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Section 1: Using the library

To use the numpy library, we need to import it into python environment. I Google colab, its already available so to import the numpy library use import statement. We can rename the imported library to a shorter name for our convenience

In [2]:
import numpy as np

## Why use numpy?

*   Numpy arrays are faster and efficient than python arrays
*   Numpy has built in functions useful for faster calculations
*   Many libraries use numpy arrays to improve the performance

#Section 2: Basics with numpy

First we can go through some basic operations with numpy library. In numpy, we work with arrays. In python, you use lists. They looks the same, but internally the implementation is very different.

## Create an array
The simplest way to create a numpy array is to type the values on the python scritp, however this is rarely used in practice

In [ ]:
myNPArray = np.array([1, 2, 3, 4, 5, 6])
print(myNPArray)

[1 2 3 4 5 6]


## Other ways to create numpy arrays
You can use already established python list and convert it to a numpy array


In [ ]:
pythonList = [1,2,3,4,5,6,7,8,9,10]
convertedNPArray = np.array(pythonList)
print(convertedNPArray)

[ 1  2  3  4  5  6  7  8  9 10]


#Section 3: Operations and performance
Now we know how to create a numpy array. There are other methods to create numpy arrays, but we will work with these methods first. 

To prove if numpy gives us a performance benifit, lets do a simple test with numpy. Lets assume we have a large dataset, and we want to multiply value by some number. This is useful in many applications, for example if you have an black and white (grayscale) image and you want to increase/decreas the brightness, we can read the pixel values of the image into numpy array and multiply the pixel values by a number to increase/decrease the pixel value. Since pixel values directly proportional to the bridgtness in a grayscale images we can change the brightness using a simple operation.

If you have audio data, the loudness is proportianal to the audio sample values. You can increase the loudness by multiplyig the audio sample values by a factor.

If you want to do lot of these kind of processing, numpy can be a real benificial library. For example, if you want to process a large number of audio/image files.

Lets do a simple test. Since reading audio, image require special functions out of our scope, lets create a simple array to fill our data and do the operation on this example array.

We can create an array with numpy and python and do a speed comparison



Lets creat an array with 100 million elements

In [ ]:
import time #time library to measure execution time

#make two data storage variables for numpy and python 
pythonList100000000 = list(range(1,100000001))
print(len(pythonList100000000))

numpyArray100000000 = np.arange(1,100000001)
print(len(numpyArray100000000))

multiplyNumber = 3

#measure the time it takes to multiply each value

#we use time.time() to capture system time and measure the time difference to calculate elapsed time
t1 = time.time()
out1 = [multiplyNumber*x for x in pythonList100000000]
t2 = time.time()
timediffPython = t2-t1
print(timediffPython)

#now measure how much time it takes for numpy to do the same task
t1 = time.time()
out2 = numpyArray100000000 * multiplyNumber
t2 = time.time()
timediffNumpy = t2-t1
print(timediffNumpy)

#Lets take the ratio between these two times
print("Numpy is {} times faster than a python list".format(timediffPython/timediffNumpy ))


100000000
100000000
12.417309999465942
0.23836803436279297
Numpy is 52.09301671954454 times faster than a python list


Now, since we have firsthand know numpy has a big performance advantage over standard python lists, we will learn more operations we can do with numpy

#Section 4: Basic operations with numpy


## Loading a text file as numpy array
Lets assume we have two classes, 11 A and 11 B. At the end of the term test, we have final marks for a subject for both classes. There are 50 students in the class and the marks are stored in a CSV file.


In [ ]:
#These are the paths to data files of class list

class1_data_path = "https://raw.githubusercontent.com/GPrathap/pythonII/master/dataset/class_list/class1_marks.csv"
class2_data_path = "https://raw.githubusercontent.com/GPrathap/pythonII/master/dataset/class_list/class2_marks.csv"

## Read data
Numpy has the builtin feature to read data from a csv (or text) file. Lets use numpy loadtxt function to read the data as numpy arrays.
We want to make sure we load data as floating point numbers and we skip the first row because firs row is dedicated to the column header.

After reading, we can print the length of class data to make sure we have read all the available data points

In [ ]:
#read an array from a file
class1data = np.loadtxt(class1_data_path, dtype=float,skiprows=1)
class2data = np.loadtxt(class2_data_path, dtype=float,skiprows=1)
print(len(class1data))
print(len(class2data))


print(max(class1data))
print(max(class2data))

50
50
100.0
99.0


## Sorting
Lets see if we can sort the class 1 results. Numpy has sort() function to efficiently sort data


In [ ]:
sortedClass1 = np.sort(class1data);
print(sortedClass1)


[  3.   8.  13.  14.  15.  18.  21.  22.  24.  27.  30.  33.  35.  37.
  39.  40.  40.  40.  40.  43.  44.  48.  50.  52.  56.  57.  58.  59.
  60.  60.  62.  63.  65.  72.  72.  73.  74.  79.  81.  82.  82.  82.
  83.  84.  91.  93.  94.  97.  98. 100.]


We can do the same for the class 2 results


In [ ]:
sortedClass2 = np.sort(class2data);
print(sortedClass2)

[ 0.  0.  1.  3.  3.  4.  6.  7.  9. 13. 15. 16. 16. 19. 19. 21. 26. 29.
 30. 30. 32. 35. 36. 37. 37. 40. 40. 46. 48. 49. 55. 57. 58. 58. 59. 64.
 67. 71. 72. 74. 75. 76. 78. 84. 92. 95. 97. 98. 99. 99.]


## Logic operations
With this sorted array, we can do some interesting comparisons. Lets say our pass mark is 50. Can we find how many students have passed?

Numpy gives us an easy way to do the comparison. We can compare the full array against a number and numpy will give us an array containing true/false values for each and every element of the comparing array. 


In [ ]:
Cl1Passed = sortedClass1 >= 50 # this will give us an true false array
print(Cl1Passed)
Cl1PassedSum = Cl1Passed.sum(); # find total pass students
Cl1FailedSum = sortedClass1.size - Cl1PassedSum
print("Passed: ",Cl1PassedSum)
print("Failed: ",Cl1FailedSum)


[False False False False False False False False False False False False
 False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
Passed:  28
Failed:  22


##Array slicing

Array slicing is similar to normal python list convention. You can use startindex:endindex convention

Let's say you want to display all failed students, you can achieve the same with a sorted array or non-sorted array
For sorted array, its easy because we just want to cut the class in two sections

 

In [ ]:
failedCl1Array = sortedClass1[0:Cl1FailedSum]
print(failedCl1Array)

[ 3.  8. 13. 14. 15. 18. 21. 22. 24. 27. 30. 33. 35. 37. 39. 40. 40. 40.
 40. 43. 44. 48.]


The other way of finding out students satisfying a codition doesn't require a sorted array.

For example, from the original unsorted array, lests find out students who scored 50 or more. We can do this by doing a comparison that will generate true/false values array.

In [ ]:
passedindexes1 = class1data>=50 # this will compare the condition elementwise and give us an array 
print(passedindexes1)

[ True  True  True  True  True  True  True False  True  True False False
 False False False False False  True False  True  True  True False False
  True  True False False False  True  True False  True  True False  True
 False False  True  True  True False False False  True  True  True  True
 False  True]


Then, we can use this true/false index array to select the elements from the original array

In [ ]:
print(class1data) #original array
print(passedindexes1)
print(class1data[passedindexes1])


[ 82.  98.  84.  97.  83.  72.  91.   3.  62.  60.  48.  35.  30.  40.
  15.  22.  40.  72.  13.  73.  60. 100.   8.  21.  65.  94.  44.  24.
  27.  63.  82.  33.  56.  81.  18.  79.  40.  14.  50.  82.  74.  40.
  43.  37.  59.  52.  93.  58.  39.  57.]
[ True  True  True  True  True  True  True False  True  True False False
 False False False False False  True False  True  True  True False False
  True  True False False False  True  True False  True  True False  True
 False False  True  True  True False False False  True  True  True  True
 False  True]
[ 82.  98.  84.  97.  83.  72.  91.  62.  60.  72.  73.  60. 100.  65.
  94.  63.  82.  56.  81.  79.  50.  82.  74.  59.  52.  93.  58.  57.]


As you can see above, the true, false array work as indexes and we can easily select elements satisfying a condition
This could be extended in many ways


## Numpy logical operations
In the next example, lets find out the students who scored more than 90. Instead of saving the true/false array, we can use the result in shorter format as bellow

Also, we can use two conditions and use numpy logical operations to match the two scenarios. For example, we can check if students are above 45 and below 55 mark by combining two comparisons and do logical_and operation

In [ ]:
print(">90 students ",class1data[class1data>90])#print students who got more than 90
print("45-55 students ",class1data[np.logical_and((class1data>45),(class1data<55))])#print students marks between 45-55, take two arrays and take the logical and


>90 students  [ 98.  97.  91. 100.  94.  93.]
45-55 students  [48. 50. 52.]


## Simple scripts and more logical operations
Now lets write a quick loop to group students with different mark regions


In [ ]:
markCutoffs = [35,50,65,75,85,100] #these are our cutoff marks
tmpClass1Data = np.array(class1data, copy=True)  
for cutoff in markCutoffs:
  indexes = tmpClass1Data>=cutoff
  aboveCutoff = tmpClass1Data[indexes]
  belowCutoff = tmpClass1Data[np.logical_not(indexes)]
  print("<",cutoff," ",np.sort(belowCutoff)," sum = ",len(belowCutoff))
  tmpClass1Data = aboveCutoff

< 35   [ 3.  8. 13. 14. 15. 18. 21. 22. 24. 27. 30. 33.]  sum =  12
< 50   [35. 37. 39. 40. 40. 40. 40. 43. 44. 48.]  sum =  10
< 65   [50. 52. 56. 57. 58. 59. 60. 60. 62. 63.]  sum =  10
< 75   [65. 72. 72. 73. 74.]  sum =  5
< 85   [79. 81. 82. 82. 82. 83. 84.]  sum =  7
< 100   [91. 93. 94. 97. 98.]  sum =  5


#Section 5: Currupted or not available data

Lets say, class2 data is tentative for three student, we can mark these students as np.nan which is a way to tell numpy thate these are not a numbers. 

In [ ]:
class2data[[5,8,20]] = np.nan #we are using multiple indexes to assign a value
#now 5th, 8th, and 20th student doesn't have valid numbers
print(class2data)

[ 0. 99. 98. 97.  3. nan 40. 37. nan  1. 40. 58. 13. 57. 92. 19. 71.  3.
  4. 78. nan 36. 84. 15. 49. 75.  6. 37. 99. 67. 19. 46. 59. 35. 30. 74.
 55. 30. 95. 29.  7. 26. 72. 16.  9. 76. 21. 32. 16. 64.]


Now lets see what happen if we get the class average


In [ ]:
np.average(class2data) #the output is also a not-a-number because we try to do mathematical operations with nan

nan

## Numpy masks
To deal with this kind of situations, we can use numpy mask


In [ ]:
maskedCl2 = np.ma.masked_invalid(class2data)
print(class2data)
print(maskedCl2)
print(np.average(maskedCl2)) #the size of the array doesn't change, but with masked arrays we can avoid invalid data causing problems

[ 0. 99. 98. 97.  3. nan 40. 37. nan  1. 40. 58. 13. 57. 92. 19. 71.  3.
  4. 78. nan 36. 84. 15. 49. 75.  6. 37. 99. 67. 19. 46. 59. 35. 30. 74.
 55. 30. 95. 29.  7. 26. 72. 16.  9. 76. 21. 32. 16. 64.]
[0.0 99.0 98.0 97.0 3.0 -- 40.0 37.0 -- 1.0 40.0 58.0 13.0 57.0 92.0 19.0
 71.0 3.0 4.0 78.0 -- 36.0 84.0 15.0 49.0 75.0 6.0 37.0 99.0 67.0 19.0
 46.0 59.0 35.0 30.0 74.0 55.0 30.0 95.0 29.0 7.0 26.0 72.0 16.0 9.0 76.0
 21.0 32.0 16.0 64.0]
44.4468085106383


In [ ]:
#we can get more details for masked array

print("masked array indexes ",np.flatnonzero(maskedCl2.mask))

masked array indexes  [ 5  8 20]


This shows that we have non-zero values on the masked array at these points, indicating we have 3 nan values, and places

#Exercise 1: Simple array creation

Create an array contains numbers in ascending order 1 to 10 and descending order 10:1
The array should look like [1...10...1]
There are many ways to achieve this task. Using np.arange() and np.concatenate() is a good way to do this


In [10]:
ar1 = np.arange(1,10);
ar2 = np.arange(10,0,-1)
arFinal = np.concatenate((ar1,ar2),axis=0)
print(ar1)
print(ar2)
print(arFinal)

[1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10  9  8  7  6  5  4  3  2  1]
