<a href="https://colab.research.google.com/github/kts-desilva/pythonII/blob/master/sec_numpy/numpy_exercises_set1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Section 01: Creating, Reading and Writing නිර්මාණය කිරීම, කියවීම සහ ලිවීම**

Let's import Numpy library.

In [1]:
import numpy as np

Let's load the necessary datasets

In [20]:
class1_data_path = "https://raw.githubusercontent.com/GPrathap/pythonII/master/dataset/class_list/class1_marks.csv"
class2_data_path = "https://raw.githubusercontent.com/GPrathap/pythonII/master/dataset/class_list/class2_marks.csv"

In [21]:
#read an array from a file
class1_data = np.loadtxt(class1_data_path, dtype=float, skiprows=1)
class2_data = np.loadtxt(class2_data_path, dtype=float, skiprows=1)

#Exercise 1: Simple array creation

**Question 01**

Create an array contains numbers in ascending order 1 to 10 and descending order 10:1
The array should look like [1...10...1]

There are many ways to achieve this task. Using np.arange() and np.concatenate() is a good way to do this


**Answer**

In [8]:
ar1 = np.arange(1,10);
ar2 = np.arange(10,0,-1)
ar_final = np.concatenate((ar1,ar2),axis=0)
print(ar1)
print(ar2)
print(ar_final)

[1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10  9  8  7  6  5  4  3  2  1]


# Exercise 2: Array shape and dimension

**Quesion 01**

Convert the following 1-D array with 12 elements into a 3-D array.

**Hint:** *The new array should contain 3 rows*

In [9]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

**Answer**

In [10]:
ar_final = ar.reshape(3,4)
print(ar_final)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Question 02**

Reshape the following array which has the shape (6,) to (6,1)

**Hint:** *Try to use Numpy newaxis function*

In [17]:
ar = np.array([10, 50, 15, 59, 5, 42])
print(ar.shape)

(6,)


**Answer**

In [19]:
ar_final = ar[:, np.newaxis]
print(ar_final.shape)

(6, 1)


# Exercise 3: Array splicing and staking

**Question 1:**

**Part 1**

Calculate the z-score for the class 1 marks.

z score = (student mark - mean of the marks) / standard diviation

In [34]:
class1_mean = np.mean(class1_data)
class1_standard_diviation = np.std(class1_data)

class1_zscore = (class1_data - class1_mean) / class1_standard_diviation
class1_zscore = class1_zscore.round(2)

print(class1_zscore)

[ 1.05  1.65  1.12  1.61  1.08  0.67  1.39 -1.93  0.29  0.22 -0.24 -0.73
 -0.92 -0.54 -1.48 -1.22 -0.54  0.67 -1.56  0.71  0.22  1.73 -1.74 -1.25
  0.41  1.5  -0.39 -1.14 -1.03  0.33  1.05 -0.8   0.07  1.01 -1.37  0.93
 -0.54 -1.52 -0.16  1.05  0.74 -0.54 -0.42 -0.65  0.18 -0.09  1.46  0.14
 -0.58  0.1 ]


Merge the two arrays of the student marks to a single array which should show the student marks as follows.


In [28]:
arr1 = ['student_mark', 'student_zscore']
print(arr1)

['student_mark', 'student_zscore']


**Answer**

In [45]:
class1_completed_data = np.column_stack((class1_data, class1_zscore))
print(class1_completed_data)

[[ 8.20e+01  1.05e+00]
 [ 9.80e+01  1.65e+00]
 [ 8.40e+01  1.12e+00]
 [ 9.70e+01  1.61e+00]
 [ 8.30e+01  1.08e+00]
 [ 7.20e+01  6.70e-01]
 [ 9.10e+01  1.39e+00]
 [ 3.00e+00 -1.93e+00]
 [ 6.20e+01  2.90e-01]
 [ 6.00e+01  2.20e-01]
 [ 4.80e+01 -2.40e-01]
 [ 3.50e+01 -7.30e-01]
 [ 3.00e+01 -9.20e-01]
 [ 4.00e+01 -5.40e-01]
 [ 1.50e+01 -1.48e+00]
 [ 2.20e+01 -1.22e+00]
 [ 4.00e+01 -5.40e-01]
 [ 7.20e+01  6.70e-01]
 [ 1.30e+01 -1.56e+00]
 [ 7.30e+01  7.10e-01]
 [ 6.00e+01  2.20e-01]
 [ 1.00e+02  1.73e+00]
 [ 8.00e+00 -1.74e+00]
 [ 2.10e+01 -1.25e+00]
 [ 6.50e+01  4.10e-01]
 [ 9.40e+01  1.50e+00]
 [ 4.40e+01 -3.90e-01]
 [ 2.40e+01 -1.14e+00]
 [ 2.70e+01 -1.03e+00]
 [ 6.30e+01  3.30e-01]
 [ 8.20e+01  1.05e+00]
 [ 3.30e+01 -8.00e-01]
 [ 5.60e+01  7.00e-02]
 [ 8.10e+01  1.01e+00]
 [ 1.80e+01 -1.37e+00]
 [ 7.90e+01  9.30e-01]
 [ 4.00e+01 -5.40e-01]
 [ 1.40e+01 -1.52e+00]
 [ 5.00e+01 -1.60e-01]
 [ 8.20e+01  1.05e+00]
 [ 7.40e+01  7.40e-01]
 [ 4.00e+01 -5.40e-01]
 [ 4.30e+01 -4.20e-01]
 [ 3.70e+01